apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod-deployment
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis-pod-container
          image: redis:latest
          ports:
            - containerPort: 6379
