apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-deployment
  namespace: sample
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-pod-container
          image: nginx:stable-perl
          ports:
              - containerPort: 80
          envFrom:
            - configMapRef:
                name: sample-configmap