apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-deployment
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-pod-container
          image: nginx:{{ .Values.configmap.image.tag }}
          ports:
              - containerPort: 80
          envFrom:
            - configMapRef:
                name: sample-configmap